#!/usr/bin/with-contenv bash

if [[ $VERSION != "" ]]; then
    echo "Installing new Radarr version: $VERSION"
    rm -rf /app/*

    radarr_tag="v$VERSION"
    mkdir -p /app
    curl -o /tmp/radarr.tar.gz -L \
            "https://github.com/Radarr/Radarr/releases/download/${radarr_tag}/Radarr.develop.${radarr_tag#v}.linux.tar.gz"
    tar ixzf /tmp/radarr.tar.gz -C /app --strip-components=1

    rm -rf /tmp/*
    chown -R hotio:hotio /app
fi
